from kalgo import WordCharacter, Translator

translator = Translator()

zero = WordCharacter(48,"images/0.jpg")
one = WordCharacter(49,"images/1.jpg")
two = WordCharacter(50,"images/2.jpg")
three = WordCharacter(51,"images/3.jpg")
four = WordCharacter(52,"images/4.jpg")
five = WordCharacter(53,"images/5.jpg")
six = WordCharacter(54,"images/6.jpg")
seven = WordCharacter(55,"images/7.jpg")
eight = WordCharacter(56,"images/8.jpg")
nine = WordCharacter(57,"images/9.jpg")

A = WordCharacter(65,"images/A1.jpg" )
B = WordCharacter(66,"images/B1.jpg" )
C = WordCharacter(67,"images/C1.jpg" )
D = WordCharacter(68,"images/D1.jpg" )
E = WordCharacter(69,"images/E1.png" )
F = WordCharacter(70,"images/F1.jpg" )
G = WordCharacter(71,"images/G1.jpg" )
H = WordCharacter(72,"images/H1.jpg" )
I = WordCharacter(73,"images/I1.jpg" )
J = WordCharacter(74,"images/J1.jpg" )
K = WordCharacter(75,"images/K1.jpg" )
L = WordCharacter(76,"images/L1.jpg" )
M = WordCharacter(77,"images/M1.jpg" )
N = WordCharacter(78,"images/N1.jpg" )
O = WordCharacter(79,"images/O1.jpg" )
P = WordCharacter(80,"images/P1.jpg" )
Q = WordCharacter(81,"images/Q1.jpg" ) 
R = WordCharacter(82,"images/R1.jpg" )
S = WordCharacter(83,"images/S1.jpg" )
T = WordCharacter(84,"images/T1.jpg" )
U = WordCharacter(85,"images/U1.jpg" )
V = WordCharacter(86,"images/V1.jpg" )
W = WordCharacter(87,"images/W1.jpg" )
X = WordCharacter(88,"images/X1.jpg" )
Y = WordCharacter(89,"images/Y1.jpg" )
Z = WordCharacter(90,"images/Z1.jpg")

a = WordCharacter(97,"images/a.jpg")
b = WordCharacter(98,"images/b.jpg")
c = WordCharacter(99,"images/c.jpg")
d = WordCharacter(100,"images/d.jpg")
e = WordCharacter(101,"images/e.jpg")
f = WordCharacter(102,"images/f.jpg")
g = WordCharacter(103,"images/g.jpg")
h = WordCharacter(104,"images/h.jpg")
i = WordCharacter(105,"images/i.jpg")
j = WordCharacter(106,"images/j.jpg")
k = WordCharacter(107,"images/k.jpg")
l = WordCharacter(108,"images/l.jpg")
m = WordCharacter(109,"images/m.jpg")
n = WordCharacter(110,"images/n.jpg")
o = WordCharacter(111,"images/o.jpg")
p = WordCharacter(112,"images/p.jpg")
q = WordCharacter(113,"images/q.jpg")
r = WordCharacter(114,"images/r.jpg")
s = WordCharacter(115,"images/s.jpg")
t = WordCharacter(116,"images/t.jpg")
u = WordCharacter(117,"images/u.jpg")
v = WordCharacter(118,"images/v.jpg")
w = WordCharacter(119,"images/w.jpg")
x = WordCharacter(120,"images/x.jpg")
y = WordCharacter(121,"images/y.jpg")
z = WordCharacter(122,"images/z.jpg")




translator.add_character(D)
translator.add_character(E)
translator.add_character(H)
translator.add_character(L)
translator.add_character(O)
translator.add_character(R)
translator.add_character(W)


translator.generate_train_data()
translator.train("sample/8.png")
